#!/bin/bash
#
# chkconfig: 2345 97 3
# description: registry.

case "$1" in
  start)
        echo "Start"
        docker run -v /opt/registry:/var/lib/registry -p 8000:5000 registry 2>&1 > /var/log/myregistry.log &
        ;;
  stop)
        echo "Stop"
ps -ef | grep "docker run" | grep registry | head -1 | while read user pid rest
do
  echo "stopping $rest"
  kill $pid
done

        ;;
  *)
        echo $"Usage: registry {start|stop}"
esac
